/**
 * TreeNode represents a single structural node within the document hierarchy (PageIndex Model).
 */
export class TreeNode {
  /**
   * @param {Object} params
   * @param {string} params.nodeId - Unique identifier (e.g. 'ch_2', 'sec_2_2')
   * @param {string} params.title - Human readable section or chapter title
   * @param {number} params.level - Hierarchy depth (0 = Root, 1 = Chapter, 2 = Section)
   * @param {number[]} params.pageRange - [startPage, endPage]
   * @param {string} params.summary - High-density semantic abstract generated by LLM
   * @param {string[]} [params.keywords=[]] - Domain topic tags
   * @param {string[]} [params.entities=[]] - Key named entities
   * @param {string} [params.content=""] - Targeted raw section text (lazy-loaded)
   * @param {string|null} [params.parentId=null] - Parent node ID
   */
  constructor({
    nodeId,
    title,
    level,
    pageRange,
    summary,
    keywords = [],
    entities = [],
    content = "",
    parentId = null
  }) {
    this.nodeId = nodeId;
    this.title = title;
    this.level = level;
    this.pageRange = pageRange;
    this.summary = summary;
    this.keywords = keywords;
    this.entities = entities;
    this.content = content;
    this.parentId = parentId;
    /** @type {TreeNode[]} */
    this.children = [];
  }

  /**
   * Attach a child branch to current node and bind parent pointer.
   * @param {TreeNode} childNode 
   */
  addChild(childNode) {
    childNode.parentId = this.nodeId;
    this.children.push(childNode);
  }

  /**
   * Check if current node is a leaf node (no sub-branches).
   * @returns {boolean}
   */
  isLeaf() {
    return this.children.length === 0;
  }

  /**
   * Serialize lightweight metadata payload for index storage (excluding raw text).
   * @param {boolean} [includeContent=false]
   * @returns {Object}
   */
  toMetadataJSON(includeContent = false) {
    const json = {
      nodeId: this.nodeId,
      title: this.title,
      level: this.level,
      pageRange: this.pageRange,
      summary: this.summary,
      keywords: this.keywords,
      entities: this.entities,
      parentId: this.parentId,
      childrenIds: this.children.map((child) => child.nodeId)
    };

    if (includeContent) {
      json.content = this.content;
    }

    return json;
  }
}
