/**
 * Represents a single document entry in an LLM Wiki (Karpathy Model).
 */
export class WikiFileEntry {
  /**
   * @param {Object} params
   * @param {string} params.filePath - Vault relative file path (e.g. 'infrastructure/alb-sticky-sessions.md')
   * @param {string} params.title - Human readable wiki document title
   * @param {string} params.category - Folder directory taxonomy category
   * @param {string[]} params.tags - Metadata tags
   * @param {string} params.summary - High-density semantic abstract generated by LLM Librarian
   * @param {string} params.rawContent - Full raw Markdown text content
   */
  constructor({ filePath, title, category, tags, summary, rawContent }) {
    this.filePath = filePath;
    this.title = title;
    this.category = category;
    this.tags = tags;
    this.summary = summary;
    this.rawContent = rawContent;
  }

  /**
   * Returns lightweight metadata payload for Pass 1 scan (zero raw content).
   * @returns {Object}
   */
  getMetadata() {
    return {
      filePath: this.filePath,
      title: this.title,
      category: this.category,
      tags: this.tags,
      summary: this.summary
    };
  }
}

/**
 * Manages the Wiki catalog file system vault.
 */
export class WikiVault {
  constructor() {
    /** @type {Map<string, WikiFileEntry>} */
    this.files = new Map();
  }

  /**
   * Add a file to the Wiki catalog vault.
   * @param {WikiFileEntry} entry 
   */
  addFile(entry) {
    this.files.set(entry.filePath, entry);
  }

  /**
   * Returns metadata array for ALL files in vault (Pass 1).
   * @returns {Object[]}
   */
  listCatalogMetadata() {
    return Array.from(this.files.values()).map((entry) => entry.getMetadata());
  }

  /**
   * Pass 2 lazy-load: fetches full raw text ONLY for targeted file path.
   * @param {string} filePath 
   * @returns {string}
   */
  readFileContent(filePath) {
    const entry = this.files.get(filePath);
    if (!entry) {
      throw new Error(`File '${filePath}' not found in Wiki Vault catalog.`);
    }
    return entry.rawContent;
  }
}
